### PR TITLE
Updated to php 8.0

### PR DESCRIPTION
**Pull request by ErnestStaug**
Minimal changes, I've only added `er` to the `Match` class and `match` variables.
Also upadted phpUnit to the version that supports php 8.0, because of this had to drop support for older php versions.
I guess it's okay as older PHP versions are not supported anymore...

### CODE REVIEW

**Comment by yetanotherape** [comment]
Hi Ernest! Thank you for your effort. 

I [see](https://blog.packagist.com/php-versions-stats-2020-1-edition/) that old PHP versions are still in use and I think it's better to add support of PHP 8 without dropping support for the old ones.

**Comment by ErnestStaug** [comment]
We cannot run phpUnit tests then, as the phpUnit version that supports PHP
8 dropped support for php below 7.3 :)

We could tag this as a major version upgrade as it will have breaking
changes for older php versions.

**Comment by yetanotherape** [comment]
Hmm... I'll try to read about this. Actually, I migrated to Python as a main language and don't follow PHP news 😄

**Comment by ErnestStaug** [comment]
No worries, when you have time...
Well PHP language is moving quite quickly nowadays, I work constantly on it and cannot keep it up :smile: 
Link to phpUnit [https://github.com/sebastianbergmann/phpunit/issues/4325]

**Comment by thirsch** [comment]
Well, I think all the older versions and hhvm can be dropped. Don't think that there is a big issue, if a new major version just supports >= 7.3. If there is really a fix to be made in the classes, there is always the possibility for a backport of the fix to version 1.

It would be possible to have e.g. PHPUnit 8 and PHPUnit 9, but that would only support >= 7.2 and as 7.2 is already unsupported, I think it can be dropped as well. If anyone want's to support version 1 and 2 in his project, there is always the possibility to have e.g. "^1.0|^2.0" in the composer version constraint.

**Pull request merged**
